---
title: "Homework 9"
author: "Mahima Palamanda"
date: "4/5/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus)
library(tidyverse)
library(dplyr)
library(ggplot2)
```
#Question 1
```{r}
census_api_key("a4934a6ebd0d4818e6f7431fbcc184a6abf6f6be")
install = TRUE
```
#Question 2a
```{r}
v17 <- load_variables(2015, "acs5", cache = TRUE)

print(v17,topn=5)

ca <- get_acs(geography = "county", 
              variables = c(medincome = "B01001A_011"), 
              state = "CA", 
              year = 2015)

print(ca,topn=5)
```
#Question 2b
```{r}
filterca<-ca%>%
  filter(estimate>=30000)%>%
  arrange(desc(estimate))
filterca
```
#Question 2c
```{r}
filterca%>%
  filter(estimate==51644,moe==667)
```
#Question 2d
```{r}
ggplot(filterca,mapping=aes(x=estimate))+geom_boxplot(fill="red")
```
#Question 2e
```{r}
filterca%>%
  mutate(NAME = gsub(" County, California", "", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(color = "blue", size = 3) +
  labs(title = "Median Income for White Males by County",
       subtitle = "2014-2018 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)")
```


